version: "3.8"
services:
  nats:
    image: "nats:latest"
    ports:
      - "4222:4222"

  consul:
    image: consul:latest
    ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:8600"
